export const SKIP_SUBTHEMES = [
  "Product Collection",
  "Magazine Gift",
  "Book Parts",
  "Promotional",
  "Seasonal",
  "Special",
  "Formula 1",
  "Bonus/Value Pack",
];
export const SKIP_THEMES = ["Sports", "Discovery", "Promotional"];
export const SKIP_NESTED = [
  ["Icons", "Adidas"],
  ["Icons", "Nike"],
  ["Icons", "Botanical Collection"],
  ["Icons", "Gardens of the World"],
  ["Icons", "Stadiums"],
  ["Icons", "Vehicles"],
  ["Icons", "Miscellaneous"],
  ["Icons", "Landmarks"],
  ["Icons", "Space"],
  ["Icons", "Restaurants of the World"],
  ["Creator", "Miscellaneous"],
  ["Creator", "Botanical Collection"],
  ["Creator", "Postcard"],
  ["Creator", "8 in 1"],
  ["Creator", "Bulk Set"],
  ["Creator", "Inventor Set"],
  ["Creator", ""],
];
