// missing values are ignored and next value is checked
// [theme, subtheme, name]
export default [
  [, , "{Catapult}"],
  [, "Bonus/Value Pack"],
  [, "Book Parts"],
  [, "Formula 1"],
  [, "Magazine Gift"],
  [, "Product Collection"],
  [, "Promotional"],
  [, "Seasonal"],
  [, "Special"],
  ["Creator", ""],
  ["Creator", "8 in 1"],
  ["Creator", "Botanical Collection"],
  ["Creator", "Bulk Set"],
  ["Creator", "Inventor Set"],
  ["Creator", "Miscellaneous"],
  ["Creator", "Postcard"],
  ["Discovery"],
  ["Icons", "Adidas"],
  ["Icons", "Botanical Collection"],
  ["Icons", "Gardens of the World"],
  ["Icons", "Landmarks"],
  ["Icons", "Miscellaneous"],
  ["Icons", "Nike"],
  ["Icons", "Restaurants of the World"],
  ["Icons", "Space"],
  ["Icons", "Stadiums"],
  ["Icons", "Vehicles"],
  ["Promotional"],
  ["Sports"],
];
